#!/usr/bin/with-contenv bash

set -e

echo ""
echo "***** copy files *****"
echo ""
files="
config.yaml
flaskfarm.code-workspace
init
svc
99-ff-profile.sh
"

for file in ${files}; do
    [[ ! -e "${FF_DATA}/${file}" ]] && {
        cp "/etc/flaskfarm/${file}" "${FF_DATA}/${file}" && \
        chown abc:abc "${FF_DATA}/${file}"
    }
done
unset file

source ${FF_DATA}/init
