version: "3.7"

services:
  ff-dev:
    build:
      context: .
    image: ff-dev
    container_name: ff-dev
    hostname: ff-dev.oracle
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    volumes:
      - ${YOUR_FOLDER}/flaskfarm/data-dev:/data
    environment:
      PUID: ${YOUR_PUID}
      PGID: ${YOUR_PGID}
      TZ: Asia/Seoul
